name: Azure Function App Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS}}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
         az account show
      
    - name: Get Function App Publish Profile
      uses: azure/CLI@v1
      id: get-publish-profile
      with:
        azcliversion: latest
        inlineScript: |
          profile=$(az functionapp deployment list-publishing-profiles --name acme-test-function-app --resource-group acme-test-resource-group --query "[?publishMethod=='FTP'].{url: publishingUserName, username: publishUrl}" --output tsv)
          echo "::set-output name=profile::$profile"
      
    - name: Deploy to Azure Function App
      uses: azure/webapps-deploy@v2
      with:
        app-name: acme-test-function-app
        publish-profile: ${{ steps.get-publish-profile.outputs.profile }}
